### ISSUE TITLE
streams are over roads

### ISSUE THREAD

**Issue by eringreb** [tangrams/outdoor-style#151]
Streams show overtop of trails and roads.

![image](https://cloud.githubusercontent.com/assets/18540280/23778392/df172aee-0507-11e7-9489-43c86a91ab13.png)

**Comment by nvkelso** [comment]
Oops, definitely a bug!

**Comment by nvkelso** [comment]
And @eringreb congrats for your first Github issue! :)

**Comment by eringreb** [comment]
Thanks! The map looks great. Also made me realize I tagged a bunch of trails in my local parks incorrectly since they weren't showing up colored. Fixed now!

**Comment by nvkelso** [comment]
:)

**Comment by sensescape** [comment]
@bcamper (Nathaniel writing) can you check the logic here, please? It seems like Tangram isn't evaluate the true and false correctly? 

There is a vector tile bug (https://github.com/tilezen/vector-datasource/issues/1143) that streams that are `intermittent=false` shouldn't have that property exported at all, but if Tangram sees false in the data, shouldn't that evaluate false in the test? Right now any and all waterways are drawing dashed instead :\

- https://github.com/tangrams/walkabout-style/blob/gh-pages/walkabout-style.yaml#L1502

```
intermittent:
                filter:
                    any:
                        - intermittent: true
                        - kind: drain
                draw:
                    lines:
                        visible: false
                    dots-lines:
                        order: function() { return feature.sort_rank; }
                        color: [[10,[0.472,0.834,0.890]],[14,[0.511,0.877,0.930]]]
                        width: [[10,0px],[11,0.5px],[12,1px],[13,2px],[14,3px],[15,4px],[16,5px]]
```

**Comment by bcamper** [comment]
Boolean filters actually behave differently, **as covered in the docs** ;)

https://mapzen.com/documentation/tangram/Filters-Overview/#feature-properties

> 
> A Boolean value of “true” will pass a feature that contains the named property, ignoring the property’s value. A value of “false” will pass a feature that does not contain the named property:
> 
>```
> filter:
>     kind: true
>     area: false
>```
>
> To match a property whose value is a boolean, use the list syntax:
>
>``` 
> filter:
>     boolean_property: [true]
>```

This is a quirk going back to early Tangram. I honestly think that I *meant* to implement it to match JS truthy/falsiness (e.g. "true" values include `true` but also `1`, `random string`, etc., "false" values include `false` but also `null`, `0`, etc.)... but it was implemented as existence-of-property instead and carried to ES that way.

I don't really like it, but we've avoided changing it to not break compatibility, and because there was an existing syntax that did support direct boolean matches (the list syntax with a single boolean value works because lists matches the property value to any of the values in the list).

So you can make this:

```
intermittent:
                filter:
                    any:
                        - intermittent: [true]
                        - kind: drain
```

I would also be interested in revisiting this syntax though since I am skeptical that it has every been used (or understood!) as currently written. cc @matteblair @meetar
