### ISSUE TITLE
add toggle to enable water terrain shading

### ISSUE THREAD

**Issue by nvkelso** [tangrams/outdoor-style#184]
Bathymetry data isn't always great (great = SF Bay area, not good = around Korea), so this should be an optional on thing instead of on by default.

**Comment by nvkelso** [comment]
Another option is to use a theme import for this:

```
layers:
    water:
        draw:
            polygons:
                style: terrain
```
