### ISSUE TITLE
Show path steepness 

### ISSUE THREAD

**Issue by bcamper** [tangrams/outdoor-style#44]
@nvkelso suggested we could try to show path steepness based on normal/elevation tile data.

We tried any initial prototype using the steepness of the terrain normal; deeper red means steeper terrain:

![tangram-thu may 12 2016 15-13-14 gmt-0400 edt](https://cloud.githubusercontent.com/assets/16733/15228529/93e4bf04-185a-11e6-9bc4-7ca6dbdd6dac.png)

But, this isn't really right, because the steepness of the terrain does not necessarily equal the steepness of the path, e.g. a steep path could be _going up_ a mountain, but a relatively flat path could also simply be going _around_ a steep mountain. We can see this in the path above N. Valley Trail, where the mountain itself is steep, but the path appears to be going alongside the mountain.

To know how steep the path itself is, we need to take the _dot product of path direction and the terrain normal_ (actually the xy component of the terrain normal since path direction is 2D). That gives something that (on first glance) looks closer to what we might expect: that same path above N. Valley Trail is mostly flat, but you can see steeper red segments that correspond to variations in the terrain itself.

![tangram-thu may 12 2016 16-15-32 gmt-0400 edt](https://cloud.githubusercontent.com/assets/16733/15229821/ad007f7c-1860-11e6-8b5e-2aa2578ad403.png)

This remains a prototype, however, more experimentation is needed to verify that this behavior is correct, and consider better ways to deal with caps ad joins on lines.

Another approach to consider, that may make more sense overall, is to just sample the _raw elevation change_ of each path segment. There is no way to do that with existing Tangram pipeline though; options could include a) sampling the elevation in the vertex shader to create a custom varying and then measure the screenspace derivative of the elevation change (though there isn't 100% device support for vertex shader texture sampling, particularly on mobile devices), or b) a hook somewhere in the tile build process to do this CPU side (complicated by texture load timing and might imply a lot of new syntax that could be difficult to support cross-platform).

**Comment by bcamper** [comment]
Here's the current scene file I was experimenting with, for posterity:

[terrain-path-steepness.txt](https://github.com/tangrams/outdoor-style/files/262266/terrain-path-steepness.txt)

github only allows txt extensions, not yaml :/

**Comment by nvkelso** [comment]
(This would also be useful for bike map.)

**Comment by bcamper** [comment]
I'll dust off the test code and try it out again :)

**Comment by bcamper** [comment]
I've been looking at this with @meetar. There are two issues I'm unsure about that are holding back the quality/usefulness:

- Is the current terrain data is high resolution enough to make this work for paths.
- Do we currently have access to the necessary path direction information within the line shader (the example below approximates it, but line joins interfere); this is solvable with additional (optional) vertex attributes if needed though.

Here's a demo of current WIP, putting this down again for the moment - white path area is "flat", redder is steeper:
https://mapzen.com/tangram/play/?lines=876-911&scene=https%3A%2F%2Fmapzen.com%2Fapi%2Fscenes%2F4%2F372%2Fresources%2Fwalkabout-style.yaml#16.0000/36.0887/-112.1627

**Comment by bcamper** [comment]
Here's a variant showing the surrounding terrain steepness - black is flat, whiter is steeper:

https://mapzen.com/tangram/play/?lines=999&scene=https%3A%2F%2Fmapzen.com%2Fapi%2Fscenes%2F4%2F373%2Fresources%2Fwalkabout-style.yaml#16.0000/36.0887/-112.1627

There's a uniform `u_show_steepness` on line 999 you can use to toggle that on/off.

**Comment by nvkelso** [comment]
This is super rad! Screenshots of San Francisco:

<img width="807" alt="screen shot 2017-03-16 at 13 49 30" src="https://cloud.githubusercontent.com/assets/853051/24018012/7387e9d8-0a4f-11e7-92c3-9b0fd3dbc5b1.png">

<img width="733" alt="screen shot 2017-03-16 at 13 49 42" src="https://cloud.githubusercontent.com/assets/853051/24018011/736fb7d2-0a4f-11e7-8aa4-e802c2aebf3b.png">

SRTM only terrain data doesn't fair so well (is too radar bumpy), here Munich:

<img width="431" alt="screen shot 2017-03-16 at 13 50 42" src="https://cloud.githubusercontent.com/assets/853051/24018059/a527af82-0a4f-11e7-8f07-ae8204d0f002.png">

**I've made adjustments to the style here:**

- https://mapzen.com/tangram/play/?scene=https://mapzen.com/api/scenes/506/376/resources/walkabout-style.yaml#13.0000/37.7658/-122.4396

The key bits are:

Add the slope style to draw block, giving it width and order (this is for quick data exploration, would need to be reworked for final display):

```
    roads:
        draw:
            slope2:
                width: [[13,1px],[15,2px],[17,3m]]
                color: red
                order: function() { return feature.sort_rank +100; }
        path:
            draw:
                # not clear why this is needed again, and why width isn't 
                slope2:
                    width: [[13,1px],[15,6px],[17,3m]]    honored
                    color: red
                    order: function() { return feature.sort_rank + 0100; }
            footway:
                # because sidewalks are close to tall buildings, then the slopes are all wonky
                sidewalk-crossing:
                        slope2:
                            visible: false
````

The style is defined as:

```
styles:
    slope2:
        base: lines
        raster: custom
        shaders:
            blocks:
                global: |
                    varying vec2 v_path;
                position: |
                    v_path = abs(extrude.yx);
                color: |
                    vec2 path = normalize(v_path);
                    const float pathsegs = 2.;
                    path = floor(path * pathsegs) / pathsegs;
                    path = normalize(path);

                    vec3 terrain = (sampleRaster(0).rgb - .5) * 2.4;

                    float steepness = clamp(pow(dot(path, terrain.xy) * 16., 1.5), -1., 1.);
                    const float segs = 5.;
                    steepness = floor(steepness * segs) / segs;

                    color.rgb = mix(vec3(1.), vec3(1.,0.,0.), abs(steepness));
```
