### ISSUE TITLE
Prioritize existing basic outdoor POI labels

### ISSUE THREAD

**Issue by nvkelso** [tangrams/outdoor-style#5]
The following often appear on outdoor maps and are probably included in our current base maps, but at later zooms. For the outdoor style, let's relax visibility rules to show these as soon as they are visible in tiles (remove early zoom filters).

- [ ] `lighthouse`
- [ ] `peak`
- [ ] `airport`
- [ ] `saddle` (aka "mountain pass", OSM tagging funk)
- [ ] `picnic_area`
- [ ] `camp_site` aka "campground"
- [ ] `ski area`
- [ ] `mine`
- [ ] `zoo`
- [ ] `museum`
- [ ] `park`
- [ ] `gate`
- [ ] `phone`
- [ ] `water`
- [ ] `gas`

**Comment by nvkelso** [comment]
Expanded this section:

```
outdoor-has-icons:
                filter: { kind: [outdoor, lighthouse, peak, saddle, picnic_area, camp_site, ski, mine, zoo, museum, gas, gas_canister] }
                draw: 
                    icons:
                        order: 41
                        visible: function() { if( feature.min_zoom <= $zoom ) { return true; } else { return false; } }
                    text-blend-order:
                        order: 42
```
